# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Create ZIP file

on:
  release:
    types: [ prereleased ]

#on:
#  push:
#    branches:
#      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: echo release
        run: echo $RELEASE
        env:
          RELEASE: ${{ steps.get_version.outputs.VERSION }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          command: update

      - name: Remove GIT files
        run: |
          sudo rm -rf .git .github output.log docker_tag DOCKER_ENV vendor/symfony/console

      - name: Create ZIP file
        run: |
          zip -r koality-io.zip .

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: koality-io.zip
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}

      - name: Remove Screenshots & ZIP
        run: |
          rm -rf assets koality-io.zip

      - name: Create ZIP file
        run: |
          zip -r koality.zip .

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: koality.zip
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
