# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Upload to WordPress.org

on:
  release:
    types: [ released ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: echo release
        run: echo $RELEASE
        env:
          RELEASE: ${{ steps.get_version.outputs.VERSION }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          command: update

      - name: Remove GIT files
        run: |
          sudo rm -rf .git .github output.log docker_tag DOCKER_ENV

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          include: "src/"
          find: "##KOALITY_VERSION##"
          replace: ${{ RELEASE }}

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: koality-io
